name: Dependabot Auto-Approve
on:
  workflow_run:
    workflows: ["Android CI"]
    types:
      - completed

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.actor == 'dependabot[bot]' && github.repository == 'calebcav/dependabot-playground' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.workflow_run.pull_requests[0].html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
