name: Dependabot Auto-Approve
on: pull_request

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Install GitHub CLI
      #   run: sudo apt-get install gh -y

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GH_TOKEN }}"
          skip-commit-verification: true
          skip-verification: true

      - name: Approve a PR
        run: gh pr review --approve "${{ steps.metadata.outputs.pr_html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
