name: Dependabot Auto-Approve
on:
  workflow_run:
    workflows: ["Android CI"] # Replace with the name of your CI workflow
    types:
      - completed

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.actor == 'dependabot[bot]' &&
      github.repository == 'calebcav/dependabot-playground' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve a PR
        run: gh pr review --approve "${{ steps.metadata.outputs.pr_html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
